Add file uploads
ielm/utapi-rs pull request #3
Opened 2024-03-06 15:34 UTC by malaow3

Initial (rough) implementation of file uploading.

2024-03-06 15:36 UTC, malaow3 commented
Closes #2 as well.

2024-03-08 18:57 UTC, ielm requested changes
I think overall this is an excellent implementation. There are just a couple of changes requested to ensure adherence to conventions and for ease of maintenance. At some point I would also like to add tests to set up CI as well, but that's out of scope for this PR. 

Thanks again for tackling this!

2024-03-08 18:57 UTC, ielm commented on src/models/upload_files.rs
> +pub enum ACL {
Should we follow the naming conventions here? Rename to `Acl` instead of `ACL`?

2024-03-08 18:57 UTC, ielm commented on src/models/upload_files.rs
> +pub enum ACL {
https://github.com/rust-lang/rfcs/blob/master/text/0430-finalizing-naming-conventions.md#general-naming-conventions

2024-03-08 18:57 UTC, ielm commented on src/models/upload_files.rs
> +    #[serde(rename = "presignedUrl", default = "default_string")]
I think we can just use the Serde default here since String defines a default for us. 

```rust
// ...
#[serde(rename = "presignedUrl", default)]
pub presigned_url: String, 
// ...
```

2024-03-08 18:57 UTC, ielm commented on src/models/upload_files.rs
> +fn default_string() -> String {
Maybe remove this? See above comment

2024-03-08 18:57 UTC, ielm commented on src/models/upload_files.rs
> +fn default_string() -> String {
Maybe remove this? See above comment

2024-03-08 18:57 UTC, ielm commented on src/models/upload_files.rs
> +}
Another note to simply use the derived default here for empty strings

2024-03-08 18:57 UTC, ielm commented on src/utapi.rs
> +    ) -> Result<Response, anyhow::Error> {
<img src="https://media0.giphy.com/media/GCvktC0KFy9l6/giphy.gif"/>

2024-03-08 18:57 UTC, ielm commented on src/utapi.rs
> +                        ACL::PublicRead => "public-read",
Another note to rename `ACL` to `Acl` for convention reasons

2024-03-08 18:57 UTC, ielm commented on src/utapi.rs
> +                tokio::task::spawn(async move {
This looks great! Let's be careful here to avoid the cancellation issue, just in case: https://google.github.io/comprehensive-rust/async/pitfalls/cancellation.html

2024-03-08 18:57 UTC, ielm commented on src/utapi.rs
> +        do_the_thing: F,
Love the name lol but can we be more explicit with function naming? Not completely sold that a closure here is the best approach to this. [Lines 585-619](https://github.com/ielm/utapi-rs/pull/3/files#diff-5becb97b32b48d0afcc24346022464ac63d7f6cfaa9274bdae58cf0e4406c7c2R585-R619) seem like they can be broken out into a separate function rather than being anonymous. The closure is clever, but I think it overcomplicates the code a bit. What do you think?

2024-03-08 18:57 UTC, ielm commented on src/utapi.rs
> +const MAXIMUM_BACKOFF_MS: u64 = 64 * 1000;
Should we move these constants to the top of the file?

2024-03-08 18:57 UTC, ielm commented on Cargo.toml
>  serde_derive = "^1.0"
If you pull from main, the serde_derive dep has been removed in favor of the serde derive feature :)

2024-03-08 18:57 UTC, ielm commented on src/utapi.rs
Can we please add doc comments to each of the newly added functions?

2024-03-08 19:14 UTC, malaow3 commented on src/utapi.rs
> +        do_the_thing: F,
I'm cool with a refactor, was just mirroring how the functionality was written in the JS/TS ecosystem which maybe is a mistake

2024-03-08 19:21 UTC, malaow3 commented
Will go thru and make the appropriate changes, thanks for the review!

2024-03-09 01:45 UTC, malaow3 commented
Think I hit everything, just let me know if there is any other changes you would like!

2024-03-09 12:23 UTC, ielm approved these changes
Awesome thanks so much, this looks great!

<img src="https://media0.giphy.com/media/RipfZWzjUDH25euMpM/giphy.gif"/>

2024-03-09 12:27 UTC, merged